mdaffin/loopdev

losetup/src/main.rs
src/lib.rs

Allow setting the `sizelimit` parameter when attaching a file to a loopback device.

Allow setting sizelimit when attaching file.

---

Cargo.toml
README.md
losetup/Cargo.lock
losetup/Cargo.toml
losetup/src/main.rs
src/lib.rs

A collection of changes for version 0.2.0
Since we had to change the api slightly and deprecate some methods a minor version bump is required.
- `attach` is now `attach_with_offset` and `attach_file` and `attach_with_sizelimit` have been added.
- `get_path` is now just `path` to better follow rusts naming conventions.
These methods will continue to exist until at least 0.3.0 but have been marked as deprecated.

Version 0.2.0

---

Cargo.toml

A braking change was introduced and this is a reminder that a minimum version bump to 0.3.0 will be required for the next release. This also avoid confusion as to what version is being used if it is a -dev version then it will not be an offically released version.

Bumps the version to 0.3.0-dev

---

src/lib.rs

This is required in order to use an ISO as a loopback device.
```rust
fn mount_iso_to_loopback<I: AsRawFd, L: AsRawFd>(
iso: &I,
loopback: &L
) -> io::Result<()> {
let result = unsafe {
libc::ioctl(
loopback.as_raw_fd(),
LOOP_SET_FD,
iso.as_raw_fd()
)
};
if result < 0 {
Err(io::Error::last_os_error())
} else {
Ok(())
}
}
```

Implement AsRawFd for LoopDevice

---

Vagrantfile

Building the project on Vagrant after running commands on README results in error for missing 'cc' linker when building libc. Installing gcc fixes this.

Add cmd to install gcc on Vagrantfile in order to build libc crate

---

src/lib.rs

It should not be public as it is internal details about how to talk to the ioctl devices.

Fixes broken tests and makes loop_info64 private

---

src/lib.rs

Android system setup loop devices at `/dev/block/loop` instead of
`/dev/loop`. Add a `cfg` directive to that sets the `LOOP_PREFIX` for
`target_os = "android"` accordingly.

Make LOOP_PREFIX target_os specific

---

Cargo.toml
build.rs
src/lib.rs
tests/util/mod.rs

Add a build.rs to generate Rust bindings for "linux/loop.h".

Replace hard coded constant with generated bindings

---

src/lib.rs

Implement AsRawFd and IntoRawFd for LoopControl and LoopDevice
Getting the raw fd of loop control can be neccecary because the
`next_free` and `attach` operation is (unfortunately) not atomic. The fd
can be used to acquire a `flock`.
Add `IntoRawFd` for `LoopDevice`.
Add `metadata` to `LoopDevice`.

Implement AsRawFd and IntoRawFd for LoopControl and LoopDevice. Add `metadata`

---

src/lib.rs

Instead of exposing `metadata` add two function to `LoopDevice` that allow access to the the `major` and `minor` number of the device.

Replace LoopDevice::metadata with major and minor

---

losetup/src/main.rs
src/lib.rs

Allow passing the read only and autoclear flag when attaching a backing file. Allow to pass a raw fd instead of a Path when attaching. Add a fn to set the direct IO flag.

Add read_only, autoclear and direct IO

---

Cargo.toml
src/lib.rs

- Removes deprecated methods
- Bumps version to 0.3.0

Removes deprecated methods

---

Cargo.toml

By default, bindgen depends on everything needed to build the bindgen
command-line tool, such as clap and its various dependencies. Disable
default-features on bindgen and just enable the minimum required
features. This reduces loopdev's full dependency tree from 54 crates to
39 crates.

Disable most features of bindgen to reduce dependencies

---

src/lib.rs

`ioctl` has a different signature in `musl` compared to `libc`
**musl**: https://git.musl-libc.org/cgit/musl/tree/src/misc/ioctl.c?h=3f701faace7addc75d16dea8a6cd769fa5b3f260#n123
```
int ioctl(int fd, int req, ...);
```
**libc**: https://man7.org/linux/man-pages/man2/ioctl.2.html
```
int ioctl(int fd, unsigned long request, ...);
```
there seems to be identical conditional for `android`, so I just updated it to deal with `musl`
with this change it compiles on both `x86_64-unknown-linux-musl` and `x86_64-unknown-linux-gnu` but I haven't tested any other target

add support for musl

---

Cargo.toml

Update `bindgen` to support riscv64gc.
Closes #46

riscv64gc support

---

tests/integration_test.rs
tests/util/mod.rs

Motivated by a quick fix I had to do in packaging in Fedora[1].
[1] https://src.fedoraproject.org/rpms/rust-loopdev/blob/rawhide/f/loopdev-fix-test.diff

Generalize some test code for multiple architectures

---

src/lib.rs

The function currently writes a value of 16 to lo_flags, but 16 is the value for LO_FLAGS_DIRECT_IO.  The intended flag, LO_FLAGS_PARTSCAN, has a value of 8 [0].
It looks like this was a regression when deprecating attach_with_partscan[1], which had the correct value of 8.  That same commit introduces this bug.
[0] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/loop.h?h=v5.15#n25
[1] https://github.com/mdaffin/loopdev/commit/1ec98260129771fdb14b064008d857f72e2d5d16

Fix the AttachOptions.part_scan function

---

src/lib.rs
tests/integration_test.rs

Add LoopControl::add for adding/creating new loop devices via the LOOP_CTL_ADD ioctl.

Add LoopControl::add

---

Vagrantfile
src/lib.rs

The ubuntu one became annoying with snap creating loopback devices breaking the fragile tests. Also disables the doc tests as they are extreamly frigile and break more then they work. `no_run` is used so they should still be built which should be good enough for ensuring they stay working.

Switch the vagrant image to an archlinux box

---

.cargo/config.toml
.github/workflows/ci.yml
Cargo.toml
Cross.toml
README.md
src/lib.rs
tests/integration_test.rs
tests/util/mod.rs

Check compilation and lints for the targets
* aarch64-linux-android
* aarch64-unknown-linux-gnu
* aarch64-unknown-linux-musl
* x86_64-unknown-linux-gnu
* x86_64-unknown-linux-musl
The loopdev crates makes use of bindgen generated code which uses system headers that can be different for different platforms. Ensure that at it at least builds.
Enabling the tests is hard with the current structure of the integration tests and safed for a later PR.

Add github actions workflow

---

tests/integration_test.rs

It tried to count the existing devices by looking at the /dev/loop* files. But these may or may not be free devices so the check for an error on existing device file was failing as the count it came up with could be added. It has been changed to try adding the device twice - the first should succeed and the second should fail. This way around we garuntee the state of the first (assuming it was not added outside of the tests).

Fixes the add_a_loop_device test
